#配置多数据源:mongodb
spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: test
  application:
    name: book-consumer

#配置服务端口
server:
  port: 7777

#配置服务发现中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka

