db:
    testurl: 127.0.0.1:27017
    testname: test
    bookurl: 192.168.1.181:27017
    bookname: book

server:
  port: 8888
spring:
  application:
    name: reader-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
