#多配置数据源
datasource:
    driver: com.mysql.jdbc.Driver
    mysql: jdbc:mysql://127.0.0.1:3306/reader
    username: root
    pwd:
    mongodb: 127.0.0.1:27017
    db: book




#服务发现中心
server:
  port: 8888
spring:
  application:
    name: reader-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka




